apiVersion: apps/v1
kind: Deployment
metadata:
  name: algomap-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algomap-backend
  template:
    metadata:
      labels:
        app: algomap-backend
    spec:
      containers:
      - name: algomap-backend
        image: tsilver1/algomap-backend:v1.1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: data-volume
        hostPath:
          path: /path/to/your/backend/data
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: /path/to/your/backend/cache
          type: DirectoryOrCreate
